# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "click" # No explicit version specified in requirementes as of now.
      - dependency-name: "PyYAML" # No explicit version specified in requirements as of now.
      - dependency-name: "*" 
        update-types: ["version-update:semver-patch"]
      - dependency-name: "black"
        update-types: ["version-update:semver-minor"]
