repos:
-   repo: https://github.com/ambv/black
    rev: 21.5b2
    hooks:
    - id: black
      language_version: python3.7
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.2
    hooks:
    -   id: flake8
