##################################################
# Black Code Formatting
##################################################
[tool.black]
line-length = 100
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.tox
  | _build
  | build
  | dist
  | env*
  | venv
)/
'''
